"""
Django settings for alipay_zzjj project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
'''
线上配置文件

'''
DEBUG = False

# 需要配置成线上的redis
REDIS_HOST = '192.168.1.118'
REDIS_PORT = '6376'
