# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistoryOrder',
            fields=[
                ('file_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='文件id')),
                ('identity_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='请求id')),
                ('data', models.TextField(blank=True, null=True, verbose_name='请求数据')),
                ('received_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='接收请求时间')),
                ('create_file_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='生成文件时间')),
                ('read_file_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='读取文件时间')),
                ('return_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='返回结果时间')),
                ('finish_tag', models.BooleanField(default=False, verbose_name='完成标记')),
            ],
            options={
                'verbose_name': '请求记录表',
                'verbose_name_plural': '请求记录表',
                'db_table': 'request_order',
            },
        ),
    ]
