# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-24 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistoryorder',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '请求成功'), ('2', '生成文件'), ('3', '读取文件'), ('4', '返回结果')], max_length=10, null=True, verbose_name='状态'),
        ),
    ]
