# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-14 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistoryorder',
            name='identity_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='请求id'),
        ),
        migrations.AlterField(
            model_name='requesthistoryorder',
            name='unique_code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='唯一标识'),
        ),
    ]
