# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0002_requesthistoryorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainOrder',
            fields=[
                ('domain_name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='域名')),
                ('ip', models.CharField(blank=True, max_length=30, null=True, verbose_name='ip')),
            ],
        ),
    ]
