# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0004_auto_20190925_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='domainorder',
            name='kind',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='网络类型'),
        ),
        migrations.AddField(
            model_name='domainorder',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='requesthistoryorder',
            name='create_file_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生成文件时间'),
        ),
        migrations.AlterField(
            model_name='requesthistoryorder',
            name='read_file_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='读取文件时间'),
        ),
        migrations.AlterField(
            model_name='requesthistoryorder',
            name='received_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='接收请求时间'),
        ),
        migrations.AlterField(
            model_name='requesthistoryorder',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='返回结果时间'),
        ),
    ]
